services:
  db:
    image: postgres:17-alpine
    container_name: playwright-db-demo-postgres
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
